name: go-boilerplate

services:
  postgres:
    container_name: vaultline-postgres
    image: postgres:18-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-app}

    volumes:
      - postgres-data:/var/lib/postgresql

    ports:
      - "127.0.0.1:${DB_HOST_PORT:-5432}:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-app}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    security_opt:
      - no-new-privileges:true


  redis:
    container_name: vaultline-redis
    image: redis:8-alpine
    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec

    volumes:
      - redis-data:/data

    ports:
      - "127.0.0.1:${REDIS_HOST_PORT:-6379}:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

    security_opt:
      - no-new-privileges:true


  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}

    restart: unless-stopped

    env_file:
      - .env

    environment:
      APP_PORT: "8080"

      DB_HOST: postgres
      DB_PORT: "5432"

      REDIS_HOST: redis
      REDIS_PORT: "6379"

      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-}

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    ports:
      - "${APP_HOST_PORT:-8080}:8080"

    init: true

    security_opt:
      - no-new-privileges:true


volumes:
  postgres-data:
  redis-data: